name: Auto Approve and Merge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  auto-approve:
    name: Auto Approve
    runs-on: ubuntu-latest
    if: github.actor == 'saurabhdaware'
    permissions:
      pull-requests: write
    steps:
    - name: Auto Approve
      uses: hmarr/auto-approve-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
  auto-merge:
    needs: auto-approve
    name: Auto Merge
    runs-on: ubuntu-latest
    if: github.actor == 'saurabhdaware'
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"
          MERGE_LABELS: ""
          MERGE_REQUIRED_APPROVALS: 1
          MERGE_FILTER_AUTHOR: saurabhdaware
